Repository Likelion-at-SMWU-13th/Spotal-FE, pull requests merged in 2025-08, with the labels that each got.

#4 Settings/#1/tailwindCSS, viewport, 전역폰트 설정
  index.html
  package-lock.json
  package.json
  src/components/fonts/Pretendard-Black.woff
  src/components/fonts/Pretendard-Bold.woff
  src/components/fonts/Pretendard-ExtraBold.woff
  src/components/fonts/Pretendard-ExtraLight.woff
  src/components/fonts/Pretendard-Light.woff
  src/components/fonts/Pretendard-Medium.woff
  src/components/fonts/Pretendard-Regular.woff
  src/components/fonts/Pretendard-SemiBold.woff
  src/components/fonts/Pretendard-Thin.woff
  src/index.css
  vite.config.js
Labels: ⚙️ Setting, 👼🏽 yeonseo

#6 Feat/#2/KakaoAPI 연동
  .gitignore
  index.html
  jsconfig.json
  package-lock.json
  package.json
  src/components/map/KakaoMap.jsx
  src/components/map/MapContainer.jsx
  src/pages/MapPage.jsx
Labels: 🦁 Parkseeun, ✨ Feature

#12 Feat/#4/온보딩 페이지 제작
  src/assets/OnBoarding1.svg
  src/assets/OnBoarding2.svg
  src/assets/OnBoarding3.svg
  src/assets/return.svg
  src/components/onboarding/FooterBtn.jsx
  src/components/onboarding/ProgressBar.jsx
  src/pages/OnBoardingPage.jsx
Labels: 👼🏽 yeonseo, ✨ Feature

#14 Feat/#13/로그인 페이지 구현
  package-lock.json
  package.json
  src/assets/Logo.svg
  src/components/auth/AuthBox.jsx
  src/components/auth/AuthBtn.jsx
  src/components/onboarding/FooterBtn.jsx
  src/pages/Login.jsx
  src/pages/OnBoardingPage.jsx
  vite.config.js
Labels: 👼🏽 yeonseo, ✨ Feature

#16 Feat/#15/recommended place component
  src/assets/BookMark.svg
  src/assets/BookMark2.svg
  src/components/recommend/RecommendedPlaces.jsx
Labels: 🦁 seeun, ✨ Feature

#22 Feat/#21/홈 페이지
  src/assets/ArrowUp.svg
  src/assets/Search.svg
  src/pages/HomePage.jsx
Labels: 🦁 seeun, ✨ Feature

#31 Feat/#30/감정 선택 페이지
  src/App.jsx
  src/assets/Highlight1.svg
  src/assets/Highlight2.svg
  src/assets/Memory1.svg
  src/assets/Memory2.svg
  src/components/map/InfoContainer.jsx
  src/components/memory/StepSelector.jsx
  src/components/recommend/RecommendedPlaces.jsx
  src/components/shared/Footer.jsx
  src/components/shared/Header.jsx
  src/components/shared/Header2.jsx
  src/pages/HomePage.jsx
  src/pages/MapPage.jsx
  src/pages/MemorySearchPage.jsx
  src/pages/RecommendedPage.jsx
Labels: 🦁 seeun, ✨ Feature

#33 Feat/#32/커뮤니티 게시글 목록 수정
  package-lock.json
  package.json
  src/components/community/Dropdown.jsx
  src/components/community/ImageSlider.jsx
  src/components/community/Post.jsx
  src/pages/CommunityPostList.jsx
Labels: 👼🏽 yeonseo, ✨ Feature

#35 Design/#32/컬러팔레트 색상 수정
  src/index.css
Labels: 👼🏽 yeonseo, 🎨 Design

#40 Feat/#39/자동 완성 기능
  src/components/map/InfoContainer.jsx
  src/components/search/SearchResults.jsx
  src/components/shared/Button.jsx
  src/index.css
  src/pages/HomePage.jsx
Labels: 🦁 seeun, ✨ Feature

#42 Feat/#41/지도 검색 범위 제한
  src/components/map/KakaoMap.jsx
  src/components/map/MapContainer.jsx
  src/components/search/SearchResults.jsx
  src/hooks/usePlaceSearch.jsx
  src/pages/HomePage.jsx
  src/pages/MapPage.jsx
Labels: 🦁 seeun, ✨ Feature

#48 Feat/45/marker image
  src/assets/Marker1.svg
  src/assets/Marker2.svg
  src/components/map/InfoContainer.jsx
  src/components/map/KakaoMap.jsx
  src/components/map/Marker.jsx
  src/components/recommend/RecommendedInfo.jsx
Labels: 🦁 seeun, ✨ Feature

#59 Feat/#57/자동 검색 연동
  src/assets/Marker1.svg
  src/assets/Marker2.svg
  src/components/map/KakaoMap.jsx
  src/components/map/MapContainer.jsx
  src/components/map/Marker.jsx
  src/components/search/SearchResults.jsx
  src/hooks/usePlaceSearch.jsx
  src/pages/HomePage.jsx
Labels: 🦁 seeun, ✨ Feature

#69 API/#68/로그인 페이지 API 연결
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: 👼🏽 yeonseo, 📬 API

#71 Feat/#67/길 찾기 기능
  src/components/map/KakaoMap.jsx
  src/components/map/MapContainer.jsx
  src/hooks/useGelocation.jsx
  src/hooks/useLoadPolyline.jsx
  src/hooks/useLoadSearch.jsx
Labels: 🦁 seeun, ✨ Feature

#73 Feat/#72/현재 위치 기반 검색
  src/components/map/KakaoMap.jsx
  src/hooks/useGelocation.jsx
  src/hooks/usePlaceSearch.jsx
Labels: 🦁 seeun, ✨ Feature

#81 Design/#80/마커 움직임
  src/components/map/InfoContainer.jsx
  src/components/map/KakaoMap.jsx
Labels: 🦁 seeun, 🎨 Design

#83 Design/#82/추천, 맵 페이지 UI
  src/components/map/InfoContainer.jsx
  src/components/recommend/RecommendedInfo.jsx
  src/components/recommend/RecommendedPlaces.jsx
  src/components/shared/Header.jsx
  src/pages/RecommendedPage.jsx
Labels: 🦁 seeun, 🎨 Design

#85 Feat/#84/이미지 변경
  src/assets/Memory2.svg
Labels: 🦁 seeun, 🌏 Deploy

#87 Design/#86/홈, 로그인, 회원가입 UI 개선
  package-lock.json
  package.json
  src/components/map/KakaoMap.jsx
  src/components/onboarding/ProgressBar.jsx
  src/components/search/SearchResults.jsx
  src/components/shared/Header.jsx
  src/components/shared/Loading.jsx
  src/pages/HomePage.jsx
  src/pages/Login.jsx
  src/pages/OnBoardingPage.jsx
  src/pages/Signup.jsx
Labels: 🦁 seeun, 🎨 Design

#95 API/#94/사용자 정보 연동
  src/components/community/ImageUploader.jsx
  src/components/community/Post.jsx
  src/components/community/PostList.jsx
  src/components/community/PostMenu.jsx
  src/pages/EditPage.jsx
  src/pages/Login.jsx
  src/pages/WritePage.jsx
Labels: 👼🏽 yeonseo, 📬 API

#99 Design/#98/커뮤니티, 온보딩, 로그인, 회원가입 등 모든 페이지 반응형 적용
  src/components/auth/AuthBox.jsx
  src/components/auth/AuthBox2.jsx
  src/components/auth/AuthBtn.jsx
  src/components/community/Dropdown.jsx
  src/components/community/Dropdown2.jsx
  src/components/community/ImageSlider.jsx
  src/components/community/ImageUploader.jsx
  src/components/community/Post.jsx
  src/components/community/PostList.jsx
  src/components/community/TagBtn.jsx
  src/components/mypage/EmotionCard.jsx
  src/components/onboarding/ProgressBar.jsx
  src/components/shared/Header.jsx
  src/components/shared/Header2.jsx
  src/pages/CommunityMyPostList.jsx
  src/pages/CommunityPostList.jsx
  src/pages/EditPage.jsx
  src/pages/Login.jsx
  src/pages/Mypage.jsx
  src/pages/OnBoardingPage.jsx
  src/pages/Signup.jsx
  src/pages/WritePage.jsx
Labels: 👼🏽 yeonseo, 🎨 Design

#104 Design/#103/지도, 알림창
  src/components/map/KakaoMap.jsx
  src/components/map/MapContainer.jsx
  src/components/search/SearchNoResults.jsx
  src/components/search/SearchNoYongsan.jsx
  src/pages/HomePage.jsx
  src/pages/RecommendedPage.jsx
Labels: 🦁 seeun, 🎨 Design

#110 Feat/#109/사진 필수 옵션 제거
  src/components/recommend/RecommendedPlaces.jsx
  src/pages/HomePage.jsx
  src/pages/RecommendedPage.jsx
Labels: 🦁 seeun, ✨ Feature

#111 API/#107/커뮤니티 게시물 필터링 연동
  src/components/community/Dropdown.jsx
  src/components/community/PostList.jsx
  src/pages/CommunityMyPostList.jsx
  src/pages/CommunityPostList.jsx
Labels: 👼🏽 yeonseo, 📬 API

#135 Fix/#130/bookmark
  src/components/auth/AuthBox.jsx
  src/components/auth/AuthBox2.jsx
  src/components/community/ImageSlider.jsx
  src/components/community/Post.jsx
  src/components/mypage/EmotionCard.jsx
  src/components/shared/Loading.jsx
  src/pages/Login.jsx
  src/pages/Mypage.jsx
  src/pages/Signup.jsx
Labels: 👼🏽 yeonseo, 🐞 Fix

#138 Feat/#67/검색 로드 수정
  src/components/search/SearchResults.jsx
Labels: 🦁 seeun, 🐞 Fix

#139 Deploy/#/카카오 테스트
  src/components/search/SearchResults.jsx
Labels: 🦁 seeun, 🌏 Deploy

#140 Deploy/vercel.json 추가
  vercel.json
Labels: 👼🏽 yeonseo, 🌏 Deploy

#142 Chore/vite.config.js 수정
  vite.config.js
Labels: 👼🏽 yeonseo, 🌏 Deploy

#146 Fix/#143/카카오 로드 수정
  src/components/search/SearchResults.jsx
  src/hooks/useKakaoScript.jsx
  src/pages/HomePage.jsx
Labels: 🦁 seeun, 🐞 Fix

#149 Design/#147/UIUX 및 추천 가게 지도&경로
  src/components/map/KakaoMap.jsx
  src/components/map/Marker.jsx
  src/components/recommend/RecommendedInfo.jsx
  src/components/recommend/RecommendedPlaces.jsx
  src/components/shared/Loading.jsx
  src/hooks/useGelocation.jsx
  src/hooks/usePlaceSearch.jsx
  src/hooks/useRecommend.jsx
Labels: 🦁 seeun, ✨ Feature, 🎨 Design

#152 Deploy/#152/최종 수정 main 푸시
  src/pages/Signup.jsx
Labels: 👼🏽 yeonseo, 🌏 Deploy
