Repository Likelion-at-SMWU-13th/Spotal-FE, pull requests merged in 2025-09, with the labels that each got.

#156 Feat/#155/게시글 수정, 작성 페이지 게시글 선택 드롭다운 추가
  src/components/community/Dropdown.jsx
  src/components/community/Dropdown2.jsx
  src/pages/EditPage.jsx
  src/pages/WritePage.jsx
Labels: 👼🏽 yeonseo, ✨ Feature

#158 Docs/#157/마이페이지 주석 추가
  src/pages/Mypage.jsx
Labels: 👼🏽 yeonseo, 📃 Docs

#162 Feat/#161/로그아웃, 프로필 이미지
  src/components/mypage/CardCarousel.jsx
  src/pages/Mypage.jsx
Labels: 🦁 seeun, ✨ Feature
